BellaBeat
================
Ruiman Diaz Suarez
05/04/2022

# Google Capstone Project: How can Bellabeat, A wellness Technology Company Play It Smart?

<br>

Bellabeat is a high-tech company that manufactures health-focused smart
products. Sršen used her background as an artist to develop beautifully
designed technology that informs and inspires women around the world.
Collecting data on activity, sleep, stress, and reproductive health has
allowed Bellabeat to empower women with knowledge about their own health
and habits. Since it was founded in 2013, Bellabeat has grown rapidly
and quickly positioned itself as a tech-driven wellness company for
women.

By 2016, Bellabeat had opened offices around the world and launched
multiple products. Bellabeat products became available through a growing
number of online retailers in addition to their own e-commerce channel
on their website. The company has invested in traditional advertising
media, such as radio, out-of-home billboards, print, and television, but
focuses on digital marketing extensively. Bellabeat invests year-round
in Google Search, maintaining active Facebook and Instagram pages, and
consistently engages consumers on Twitter. Additionally, Bellabeat runs
video ads on Youtube and display ads on the Google Display Network to
support campaigns around key marketing dates.

Sršen knows that an analysis of Bellabeat’s available consumer data
would reveal more opportunities for growth. She has asked the marketing
analytics team to focus on a Bellabeat product and analyze smart device
usage data in order to gain insight into how people are already using
their smart devices. Then, using this information, she would like
high-level recommendations for how these trends can inform Bellabeat
marketing strategy.

### Business task

Analyze Fitbit fitness tracker data to gain insights into how consumers
are using FitBit app and discover some trends for Bellabeat
strategy.this questions will guide our analysis:

-   What are some trends in smart device usage?

-   How could these trends apply to Bellabeat customers?

-   How could these trends help influence Bellabeat marketing strategy?

Key stakeholders:

-   Urška Sršen: Bellabeat’s cofounder and Chief Creative Officer
-   Sando Mur: Mathematician, Bellabeat’s cofounder and key member of
    the Bellabeat executive team
-   Bellabeat marketing analytics team: A team of data analysts guiding
    Bellabeat’s marketing strategy.

This report’s deliverables:

-   A clear summary of the business task
-   A descripion of all data sources used
-   Documentation of any cleaning or manipulation of data
-   A summary of all analysis
-   Supporting visualizations and key findings
-   High-level recommendations based on the analysis

### Prepare

The data that I’ll be using is on [Kaggle:FitBit Fitness Tracker
Data](https://www.kaggle.com/datasets/arashnic/fitbit) and it composed
by 18 files of 30 FitBit users consented submision of personal tracked
data.

the data was generated by respondents from a survey via Amazon
Mechanical Turk between 12 March 2016 to 12 May 2016.

is this data ROCCC?

-   Reliable — LOW — Not reliable as it only has 30 respondents
-   Original — LOW — Third party provider (Amazon Mechanical Turk)
-   Comprehensive — MED — Parameters match most of Bellabeat products’
    parameters
-   Current — LOW — Data is 6 years old and may not be relevant
-   Cited — LOW — Data collected from third party, hence unknown

we start by uploading the datasets we are going to use in Rstudio and
the libraries.

``` r
library(tidyverse)
sleep_day<-read.csv("sleepDay_merged.csv")
daily_activity<-read.csv("dailyActivity_merged.csv")
weightlog<-read.csv("weightLog_mod.csv")
heart<- read.csv("heartrate_seconds_merged.csv")
hourlysteps<-read.csv("hourlySteps_1.csv")
```

### Process

Here, we will process the data, clean it and give the correct format.

we check our first data frame:

``` r
str(sleep_day)
```

    ## 'data.frame':    413 obs. of  5 variables:
    ##  $ Id                : num  1.5e+09 1.5e+09 1.5e+09 1.5e+09 1.5e+09 ...
    ##  $ SleepDay          : chr  "4/12/2016 12:00:00 AM" "4/13/2016 12:00:00 AM" "4/15/2016 12:00:00 AM" "4/16/2016 12:00:00 AM" ...
    ##  $ TotalSleepRecords : int  1 2 1 2 1 1 1 1 1 1 ...
    ##  $ TotalMinutesAsleep: int  327 384 412 340 700 304 360 325 361 430 ...
    ##  $ TotalTimeInBed    : int  346 407 442 367 712 320 377 364 384 449 ...

we have 413 rows and 5 columns or variables, lets check now for
duplicates.

``` r
nrow(sleep_day[duplicated(sleep_day),])
```

    ## [1] 3

It shows that we have 3 duplicates so we proceed to delete them.

``` r
sleep_day2<- unique(sleep_day)
```

``` r
str(sleep_day2)
```

    ## 'data.frame':    410 obs. of  5 variables:
    ##  $ Id                : num  1.5e+09 1.5e+09 1.5e+09 1.5e+09 1.5e+09 ...
    ##  $ SleepDay          : chr  "4/12/2016 12:00:00 AM" "4/13/2016 12:00:00 AM" "4/15/2016 12:00:00 AM" "4/16/2016 12:00:00 AM" ...
    ##  $ TotalSleepRecords : int  1 2 1 2 1 1 1 1 1 1 ...
    ##  $ TotalMinutesAsleep: int  327 384 412 340 700 304 360 325 361 430 ...
    ##  $ TotalTimeInBed    : int  346 407 442 367 712 320 377 364 384 449 ...

After remove the duplicates next step is separate date into date and
time for further analysis.

``` r
separate(sleep_day2,SleepDay,c("date","time"),sep = " ")
```

the next data frame that we are going to manipulate is daily_activity.

``` r
str(daily_activity)
```

    ## 'data.frame':    940 obs. of  15 variables:
    ##  $ Id                      : num  1.5e+09 1.5e+09 1.5e+09 1.5e+09 1.5e+09 ...
    ##  $ ActivityDate            : chr  "4/12/2016" "4/13/2016" "4/14/2016" "4/15/2016" ...
    ##  $ TotalSteps              : int  13162 10735 10460 9762 12669 9705 13019 15506 10544 9819 ...
    ##  $ TotalDistance           : num  8.5 6.97 6.74 6.28 8.16 ...
    ##  $ TrackerDistance         : num  8.5 6.97 6.74 6.28 8.16 ...
    ##  $ LoggedActivitiesDistance: num  0 0 0 0 0 0 0 0 0 0 ...
    ##  $ VeryActiveDistance      : num  1.88 1.57 2.44 2.14 2.71 ...
    ##  $ ModeratelyActiveDistance: num  0.55 0.69 0.4 1.26 0.41 ...
    ##  $ LightActiveDistance     : num  6.06 4.71 3.91 2.83 5.04 ...
    ##  $ SedentaryActiveDistance : num  0 0 0 0 0 0 0 0 0 0 ...
    ##  $ VeryActiveMinutes       : int  25 21 30 29 36 38 42 50 28 19 ...
    ##  $ FairlyActiveMinutes     : int  13 19 11 34 10 20 16 31 12 8 ...
    ##  $ LightlyActiveMinutes    : int  328 217 181 209 221 164 233 264 205 211 ...
    ##  $ SedentaryMinutes        : int  728 776 1218 726 773 539 1149 775 818 838 ...
    ##  $ Calories                : int  1985 1797 1776 1745 1863 1728 1921 2035 1786 1775 ...

Checking for duplicates

``` r
nrow(daily_activity[duplicated(daily_activity), ]  )
```

    ## [1] 0

also looking for nulls

``` r
sum(is.null(daily_activity)) 
```

    ## [1] 0

<br> <br>

we have no nulls and cero duplicates,next we are going to focus is on
the formatting and filter some cero values in calories.

``` r
 daily_activity2<-daily_activity %>%               #we remove the entries where says 0 calories// we had 4 entries
  filter(Calories!=0)
```

format ActivityDate from chr to date

``` r
daily_activity3<-mutate(daily_activity2,ActivityDate=as.Date(ActivityDate,format= "%m/%d/%Y"))
daily_activity3<-rename(daily_activity3,Date=ActivityDate) # After change the format we give it another name "Date"
```

now we create a new column with the week days for further analysis.

``` r
daily_activity3$day_of_the_week<- weekdays(daily_activity3$Date)
daily_activity3<- daily_activity3[,c(1,2,16,3:15)]         #we rearrange the columns to make it more aesthetically pleasant  
```

Once we have formatting done the next steps is to analyse all data
frames to drw conclusions.

### Analysis

First thing to is is call the function summary to see some basic
information.

``` r
summary(daily_activity3)
```

    ##        Id                 Date            day_of_the_week      TotalSteps   
    ##  Min.   :1.504e+09   Min.   :2016-04-12   Length:936         Min.   :    0  
    ##  1st Qu.:2.320e+09   1st Qu.:2016-04-19   Class :character   1st Qu.: 3818  
    ##  Median :4.445e+09   Median :2016-04-26   Mode  :character   Median : 7441  
    ##  Mean   :4.850e+09   Mean   :2016-04-26                      Mean   : 7671  
    ##  3rd Qu.:6.962e+09   3rd Qu.:2016-05-04                      3rd Qu.:10734  
    ##  Max.   :8.878e+09   Max.   :2016-05-12                      Max.   :36019  
    ##  TotalDistance    TrackerDistance  LoggedActivitiesDistance VeryActiveDistance
    ##  Min.   : 0.000   Min.   : 0.000   Min.   :0.0000           Min.   : 0.000    
    ##  1st Qu.: 2.645   1st Qu.: 2.645   1st Qu.:0.0000           1st Qu.: 0.000    
    ##  Median : 5.265   Median : 5.265   Median :0.0000           Median : 0.220    
    ##  Mean   : 5.513   Mean   : 5.499   Mean   :0.1086           Mean   : 1.509    
    ##  3rd Qu.: 7.720   3rd Qu.: 7.713   3rd Qu.:0.0000           3rd Qu.: 2.090    
    ##  Max.   :28.030   Max.   :28.030   Max.   :4.9421           Max.   :21.920    
    ##  ModeratelyActiveDistance LightActiveDistance SedentaryActiveDistance
    ##  Min.   :0.00             Min.   : 0.000      Min.   :0.000000       
    ##  1st Qu.:0.00             1st Qu.: 1.960      1st Qu.:0.000000       
    ##  Median :0.24             Median : 3.380      Median :0.000000       
    ##  Mean   :0.57             Mean   : 3.355      Mean   :0.001613       
    ##  3rd Qu.:0.80             3rd Qu.: 4.790      3rd Qu.:0.000000       
    ##  Max.   :6.48             Max.   :10.710      Max.   :0.110000       
    ##  VeryActiveMinutes FairlyActiveMinutes LightlyActiveMinutes SedentaryMinutes
    ##  Min.   :  0.00    Min.   :  0.00      Min.   :  0.0        Min.   :   0.0  
    ##  1st Qu.:  0.00    1st Qu.:  0.00      1st Qu.:128.0        1st Qu.: 729.0  
    ##  Median :  4.00    Median :  7.00      Median :199.0        Median :1057.0  
    ##  Mean   : 21.26    Mean   : 13.62      Mean   :193.6        Mean   : 989.3  
    ##  3rd Qu.: 32.00    3rd Qu.: 19.00      3rd Qu.:264.2        3rd Qu.:1226.0  
    ##  Max.   :210.00    Max.   :143.00      Max.   :518.0        Max.   :1440.0  
    ##     Calories   
    ##  Min.   :  52  
    ##  1st Qu.:1834  
    ##  Median :2144  
    ##  Mean   :2313  
    ##  3rd Qu.:2794  
    ##  Max.   :4900

Interpreting statistical findings:

-   On average, the total steps were 7671 and the distance 5.51 km which
    is not good, the recommended by CDC should be 10000 steps and 8 km
    per day.
-   The active minutes analysis gives us a result of 81.24% of the time
    the users were doing little activity or being sedentary

From heart data frame we could check the values that we have in heart
rate to see if we can draw some conclusions

``` r
max(heart$Value)    
```

    ## [1] 203

``` r
mean(heart$Value)
```

    ## [1] 77.32842

``` r
min(heart$Value)
```

    ## [1] 36

the maximum heart rate is 203 which is above recommended,during exercise
should be 50-85% maximum rate.

``` r
summary(sleep_day2)
```

    ##        Id              SleepDay         TotalSleepRecords TotalMinutesAsleep
    ##  Min.   :1.504e+09   Length:410         Min.   :1.00      Min.   : 58.0     
    ##  1st Qu.:3.977e+09   Class :character   1st Qu.:1.00      1st Qu.:361.0     
    ##  Median :4.703e+09   Mode  :character   Median :1.00      Median :432.5     
    ##  Mean   :4.995e+09                      Mean   :1.12      Mean   :419.2     
    ##  3rd Qu.:6.962e+09                      3rd Qu.:1.00      3rd Qu.:490.0     
    ##  Max.   :8.792e+09                      Max.   :3.00      Max.   :796.0     
    ##  TotalTimeInBed 
    ##  Min.   : 61.0  
    ##  1st Qu.:403.8  
    ##  Median :463.0  
    ##  Mean   :458.5  
    ##  3rd Qu.:526.0  
    ##  Max.   :961.0

we can see that on average the users slept 419.2 min but they spent
458.5 min in bed.

### Share

findings with data visualisation

``` r
sedentary<-mean(daily_activity3$SedentaryMinutes)
lightly<-mean(daily_activity3$LightlyActiveMinutes)
farly<-mean(daily_activity3$FairlyActiveMinutes)
very_active<-mean(daily_activity3$VeryActiveMinutes)

slices<- list(farly,lightly,sedentary,very_active) 
slices_2<- c(farly,lightly,sedentary,very_active) 



percent<-paste0(c("Fairly","Lightly","Sedentary","Very Active")," ",round(100*slices_2/sum(slices_2),2 ),"%")
par(mar=c(5,5,5,5))             #sets the margins,the bigger the number the bigger the margin and hence the smallest the graph

pie(slices_2,labels = percent ,hole=0,main="Activity in minutes") 
```

![](https://github.com/RuimanDiaz/Bellabeat-Google-capstone/blob/main/pressure-1.png)<!-- --> <br> In
this pie we are looking at the proportion of the activity during the day
on average,

-   Sedentary minutes accounts for 81.24% of the total
-   Only a small percentage was dedicated to do fitness(1.75% and 1.12%)
    <br> <br> <br>

#### Day of the week where users were more active

the most active days are tuesday,wednesday and thursday.

``` r
df2<-daily_activity3 %>% 
  group_by(day_of_the_week) %>% 
  mutate(count_name=n())
  #we sort it by the name occurrences.

ggplot(df2,aes(x=reorder(day_of_the_week,-count_name)))+geom_bar(colour="black",fill="darkorange3")+labs(x="",y="Count")+theme(legend.position = "none")
```

![](Bellabeat-markdown2_files/figure-gfm/unnamed-chunk-17-1.png)<!-- -->

<br> <br>

#### Most active hours

Most of the steps happen in the morning between 7 am to 12 pm.

``` r
ggplot(hourlysteps,aes(x=StepTotal,y=Hour))+geom_col(fill="goldenrod3")
```

![](Bellabeat-markdown2_files/figure-gfm/unnamed-chunk-18-1.png)<!-- -->

### Act

As we have seen some common patterns are that most of the users don’t
use the tracking app where doing fitness they use it instead when doing
normal activities as only 2.87% of the time they were exercising,the
most active days are tuesday,wednesday and thursday having the mayority
of the steps during the morning. The Bellabeat app could collect more
individualized data about patterns in the routine like day and time of
the user and adapt this information to each individual.

<br>

Also we need to have in consideration that on average the total steps
are 7671 and 5.5 km, around 20% below recommended.The app could
recommend how far is the user from optimal values to help users to
achieve their goals.
